stages:
  - test
  - build
  - release


test_native_job:
  # Run all native tests
  stage: test
  image:
    name: $CI_REGISTRY/lucidac/firmware/hybrid-controller/platformio-build
  script:
    - apt update
    - apt install git build-essential -y
    - pio test -e native --filter native/* --filter emulated/*


test_others_job:
  # Compile all non-native test cases to check for incompatible changes in the codebase
  # This helps with noticing that a change breaks an old test case
  # This takes a fairly long time and may be disabled if it becomes too annoying
  stage: test
  allow_failure: true
  image:
    name: $CI_REGISTRY/lucidac/firmware/hybrid-controller/platformio-build
  script:
    - pio test -e teensy41 --without-uploading --without-testing --filter hardware/* --filter manual/* --ignore manual/teensy_basics/*


build_job:
  stage: build
  image:
    name: $CI_REGISTRY/lucidac/firmware/hybrid-controller/platformio-build
  script:
    - platformio run -e teensy41
    - echo ANABRID_BUILD_JOB_ID=$CI_JOB_ID > .anabrid_build_result.env
  artifacts:
    paths:
      - .pio/build/teensy41/firmware.hex
    # Save job id in artifacts for release job
    reports:
      dotenv: .anabrid_build_result.env
    expire_in: 4 weeks


release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: build_job
      artifacts: true
  script:
    - echo "Releasing binary built in build_job ${ANABRID_BUILD_JOB_ID}."
  release:
    name: 'LUCIDAC Firmware v$CI_COMMIT_TAG'
    description: 'LUCIDAC firmware release version $CI_COMMIT_TAG.'
    # tag_name is a mendatory field and can not be an empty string
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'Firmware binary hex file'
          url: '$CI_PROJECT_URL/-/jobs/${ANABRID_BUILD_JOB_ID}/artifacts/raw/.pio/build/teensy41/firmware.hex'
